### ISSUE TITLE
kind of improvement

### ISSUE THREAD

**Issue by JOduMonT** [indiehosters/docker-letsencrypt#1]
Hi Pierre;

I'm trying to modify this container to be able to 
Make a SAN multi domain ECC certificate with the command :

`acme.sh --issue -w /home/wwwroot/example.com -d example.com -d www.example.com --keylength ec-256`
ref: https://github.com/Neilpang/acme.sh

but when I'm modifying the function issue_cert in the entrypoint
I don't have the expected result.

```
function issue_cert () {
  if [ "$(ping -c1 -n $1 | head -n1 | sed 's/.*(\([0-9]*\.[0-9]*\.[0-9]*\.[0-9]*\)).*/\1/g')" == "$IP" ]; then
    acme.sh \
      --home /usr/bin \
      --issue \
      --keylength ec-256 \
      -d $1 \
      -d $2 \
      -d $3 \
      -d $4 \
      -d $5 \
      -w /html-root \
      --reloadcmd "cat $CERTS_PATH/$1/$1.cer $CERTS_PATH/$1/ca.cer $CERTS_PATH/$1/$1.key > $HAPROXY_PATH/certs/$1.pem"
  fi
}
```

I was hoping if you could give me a hint 

_BTW: SAN multi could be useful for certified postfix ;)_

**Comment by pierreozoux** [comment]
For that thing, I do, in the dockerfile:

VIRTUAL_HOST=example.com,www.example.com

But actually the www is something that is really asked by people.
We were doing it before, but not anymore.
Either we keep it in the VIRTUAL_HOST, or, we make it happen at the HAproxy level.

For postfix, I use the cert made for the web interface.
What would be the problem with that?

**Comment by JOduMonT** [comment]
Thanks for the clarification about the multi domain way with VIRTUAL_HOST=.

**For postfix;**
Maybe you have a way to do it,
but; I'm only able to active one cert per postfix configfile.

So in my case it will be :
VIRTUAL_HOST=mail.maindomain.com,mail.domain2.tld,mail.domain3.tld,mail.domain4.tld
and in this way I'll be able to not having a certification warning on the client side.

Do you manage multi-domain under the same postfix or you turn one postfix per domain ?

**Comment by pierreozoux** [comment]
I actually tell people to use `mail.indie.host`.
https://forum.indie.host/t/how-to-configure-your-email-cloud/54

Even if they have their own domain, it is a lot easier to manage.
